import { IProduct } from "./interfaces/IProduct";

export const products: IProduct[] = [
  {
    id: "1",
    name: "Apollo",
    brand: "Fenty",
    shortDescription: "Running Short",
    description: "Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
    sizes: ["S", "XS", "M", "L"],
    colours: ["#0F6450", "#2B2B2B", "#D3D2D5"],
    price: 240.1,
    inStock: true,
  },
  {
    id: "2",
    name: "Jupiter",
    brand: "Nike",
    shortDescription: "Just do it",
    description: "Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colours: ["#0F6450", "#2B2B2B", "#D3D2D5"],
    price: 150.600000,
    inStock: true,
  },
  {
    id: "3",
    name: "Saturn",
    brand: "Reebok",
    shortDescription: "Wayfarer",
    description: "Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
    sizes: [ "M", "L", "XXL"],
    colours: ["#0F6450", "#2B2B2B", "#D3D2D5"],
    price: 30.400000345,
    inStock: false,
  },
  {
    id: "4",
    name: "Marsify",
    brand: "New Balance",
    shortDescription: "Redefined balance",
    description: "Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
    sizes: ["S", "XS", "M"],
    colours: ["#0F6450", "#2B2B2B", "#D3D2D5"],
    price: 290.05,
    inStock: true,
  },
  {
    id: "5",
    name: "Venus",
    brand: "The Williams",
    shortDescription: "Ten is life",
    description: "Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
    sizes: ["M", "L"],
    colours: ["#0F6450", "#2B2B2B", "#D3D2D5"],
    price: 560,
    inStock: true,
  },
  {
    id: "6",
    name: "Mercury",
    brand: "Metallic",
    shortDescription: "Duragble",
    description: "Find stunning women's cocktail dresses and party dresses. Stand out in lace and metallic cocktail dresses and party dresses from all your favorite brands.",
    sizes: ["S", "XS", "L", "XL", "XXL"],
    colours: ["#0F6450", "#2B2B2B", "#D3D2D5"],
    price: 310.0000000475,
    inStock: true,
  },
]
